name: Renderer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  androidBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: assemble ViroCore
      run: |
        ./gradlew assembleDebug
      working-directory: ./android
    - name: Upload result ViroCore
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: viroCore
        path: |
          ./android/virocore/build/outputs/aar/*.aar
          ./android/viroreact/build/outputs/aar/*.aar
          ./android/viroar/build/outputs/aar/*.aar

  AndroidCheck:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 11
      - name: Code checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v2.2.4
        if: ${{ always() }}
        with:
          name: Viro-Lint-report
          path: |
            ./**/build/reports/lint-results.html
            ./**/**/build/reports/lint-results.html

  iosBuild:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install gpg
        run: brew install gnupg
      - name: Set XCode Version 11.2
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      - name: Install pod dependencies
        run: |
          cd ios
          pod install --verbose
        shell: bash
      - name: Xcodebuild iOS Renderer (non-static)
        run: |
          cd ios && xcodebuild \
            -workspace ViroRenderer.xcworkspace \
            -scheme ViroKit \
            -sdk iphoneos13.2 \
            -configuration Release \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
            
      - name: Upload iOS Renderer artifact
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: ios_dist.tgz
          path: ./ios/dist/
